# Global Health Policy Decision Intelligence Platform

### Notebook 01: Data Import and Understanding

**Author:** Hannah Nyakato Aine

### Objective
This notebook imports the World Bank Health, Nutrition and Population dataset and explores its structure before data cleaning and analysis.

In [2]:
import numpy as np
import pandas as pd

In [4]:
# pd.set_option ('display.max_columns', None)
# pd.set_option ('display.max_rows', 100)

df = pd.read_excel ("C:\\Users\\786\\Desktop\\document\\Global Health Policy Decision Intelligence\\data\\raw\\world_bank_health_data.xlsx", sheet_name='Data')
df.head()
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 11880 entries, 0 to 11879
Data columns (total 69 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series Name    11877 non-null  str
 1   Series Code    11875 non-null  str
 2   Country Name   11875 non-null  str
 3   Country Code   11875 non-null  str
 4   1960 [YR1960]  11875 non-null  object
 5   1961 [YR1961]  11875 non-null  object
 6   1962 [YR1962]  11875 non-null  object
 7   1963 [YR1963]  11875 non-null  object
 8   1964 [YR1964]  11875 non-null  object
 9   1965 [YR1965]  11875 non-null  object
 10  1966 [YR1966]  11875 non-null  object
 11  1967 [YR1967]  11875 non-null  object
 12  1968 [YR1968]  11875 non-null  object
 13  1969 [YR1969]  11875 non-null  object
 14  1970 [YR1970]  11875 non-null  object
 15  1971 [YR1971]  11875 non-null  object
 16  1972 [YR1972]  11875 non-null  object
 17  1973 [YR1973]  11875 non-null  object
 18  1974 [YR1974]  11875 non-null  object
 19  1975 [YR1975]  11875 non-null  object
 20  1976 [YR1976]  11875 non-null  object
 21  1977 [YR1977]  11875 non-null  object
 22  1978 [YR1978]  11875 non-null  object
 23  1979 [YR1979]  11875 non-null  object
 24  1980 [YR1980]  11875 non-null  object
 25  1981 [YR1981]  11875 non-null  object
 26  1982 [YR1982]  11875 non-null  object
 27  1983 [YR1983]  11875 non-null  object
 28  1984 [YR1984]  11875 non-null  object
 29  1985 [YR1985]  11875 non-null  object
 30  1986 [YR1986]  11875 non-null  object
 31  1987 [YR1987]  11875 non-null  object
 32  1988 [YR1988]  11875 non-null  object
 33  1989 [YR1989]  11875 non-null  object
 34  1990 [YR1990]  11875 non-null  object
 35  1991 [YR1991]  11875 non-null  object
 36  1992 [YR1992]  11875 non-null  object
 37  1993 [YR1993]  11875 non-null  object
 38  1994 [YR1994]  11875 non-null  object
 39  1995 [YR1995]  11875 non-null  object
 40  1996 [YR1996]  11875 non-null  object
 41  1997 [YR1997]  11875 non-null  object
 42  1998 [YR1998]  11875 non-null  object
 43  1999 [YR1999]  11875 non-null  object
 44  2000 [YR2000]  11875 non-null  object
 45  2001 [YR2001]  11875 non-null  object
 46  2002 [YR2002]  11875 non-null  object
 47  2003 [YR2003]  11875 non-null  object
 48  2004 [YR2004]  11875 non-null  object
 49  2005 [YR2005]  11875 non-null  object
 50  2006 [YR2006]  11875 non-null  object
 51  2007 [YR2007]  11875 non-null  object
 52  2008 [YR2008]  11875 non-null  object
 53  2009 [YR2009]  11875 non-null  object
 54  2010 [YR2010]  11875 non-null  object
 55  2011 [YR2011]  11875 non-null  object
 56  2012 [YR2012]  11875 non-null  object
 57  2013 [YR2013]  11875 non-null  object
 58  2014 [YR2014]  11875 non-null  object
 59  2015 [YR2015]  11875 non-null  object
 60  2016 [YR2016]  11875 non-null  object
 61  2017 [YR2017]  11875 non-null  object
 62  2018 [YR2018]  11875 non-null  object
 63  2019 [YR2019]  11875 non-null  object
 64  2020 [YR2020]  11875 non-null  object
 65  2021 [YR2021]  11875 non-null  object
 66  2022 [YR2022]  11875 non-null  object
 67  2023 [YR2023]  11875 non-null  object
 68  2024 [YR2024]  11875 non-null  object
dtypes: object(65), str(4)
memory usage: 6.3+ MB

Series Name      3
Series Code      5
Country Name     5
Country Code     5
1960 [YR1960]    5
                ..
2020 [YR2020]    5
2021 [YR2021]    5
2022 [YR2022]    5
2023 [YR2023]    5
2024 [YR2024]    5
Length: 69, dtype: int64

In [5]:
df.tail(10)
df=df.dropna(subset=['Country Name'])
df.shape

(11875, 69)

In [6]:
df= df.replace('..', np.nan)

In [7]:
df.tail()

,Series Name,Series Code,Country Name,Country Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
11870,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,Sudan,SDN,NaN,NaN,NaN,NaN,NaN,NaN,...,850,870,860,870,910,1100,1200,1400,1600,1600
11871,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,Syrian Arab Republic,SYR,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,100,100
11872,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,Togo,TGO,NaN,NaN,NaN,NaN,NaN,NaN,...,1100,1000,1100,990,960,890,920,920,940,940
11873,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,Uganda,UGA,NaN,NaN,NaN,NaN,NaN,NaN,...,25000,25000,22000,20000,19000,18000,18000,17000,15000,14000
11874,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,...,500,500,500,500,500,510,520,540,560,580

In [8]:
year_cols = [col for col in df.columns if "[YR" in col]

In [10]:
df[year_cols] = df[year_cols].apply(pd.to_numeric, errors="coerce")

In [11]:
df[year_cols].dtypes.unique()

array([dtype('float64')], dtype=object)

In [12]:
df["Country Name"].nunique()

25

In [13]:
sorted(df["Country Name"].unique())

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Central African Republic',
 'Chad',
 'Congo, Dem. Rep.',
 'Eritrea',
 'Gambia, The',
 'Guinea-Bissau',
 "Korea, Dem. People's Rep.",
 'Liberia',
 'Madagascar',
 'Malawi',
 'Mali',
 'Mozambique',
 'Niger',
 'Rwanda',
 'Sierra Leone',
 'Somalia, Fed. Rep.',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'Togo',
 'Uganda',
 'Yemen, Rep.']

In [14]:
df["Series Name"].nunique()

475

In [15]:
sorted(df["Series Name"].unique())

['AIDS estimated deaths (UNAIDS estimates)',
 'ARI treatment (% of children under 5 taken to a health provider)',
 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
 'Adults (ages 15+) and children (0-14 years) living with HIV',
 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV',
 'Adults (ages 15+) living with HIV',
 'Adults (ages 15-49) newly infected with HIV',
 'Age at first marriage, female',
 'Age at first marriage, male',
 'Age dependency ratio (% of working-age population)',
 'Age dependency ratio, old',
 'Age dependency ratio, young',
 'Age population, age 00, female',
 'Age population, age 00, male',
 'Age population, age 01, female',
 'Age population, age 01, male',
 'Age population, age 02, female',
 'Age population, age 02, male',
 'Age population, age 03, female',
 'Age population, age 03, male',
 'Age population, age 04, female',
 'Age population, age 04, male',
 'Age population, age 05, female',
 'Age population, age 05, male',
 'Age population, age 06, female',
 'Age population, age 06, male',
 'Age population, age 07, female',
 'Age population, age 07, male',
 'Age population, age 08, female',
 'Age population, age 08, male',
 'Age population, age 09, female',
 'Age population, age 09, male',
 'Age population, age 10, female',
 'Age population, age 10, male',
 'Age population, age 11, female',
 'Age population, age 11, male',
 'Age population, age 12, female',
 'Age population, age 12, male',
 'Age population, age 13, female',
 'Age population, age 13, male',
 'Age population, age 14, female',
 'Age population, age 14, male',
 'Age population, age 15, female',
 'Age population, age 15, male',
 'Age population, age 16, female',
 'Age population, age 16, male',
 'Age population, age 17, female',
 'Age population, age 17, male',
 'Age population, age 18, female',
 'Age population, age 18, male',
 'Age population, age 19, female',
 'Age population, age 19, male',
 'Age population, age 20, female',
 'Age population, age 20, male',
 'Age population, age 21, female',
 'Age population, age 21, male',
 'Age population, age 22, female',
 'Age population, age 22, male',
 'Age population, age 23, female',
 'Age population, age 23, male',
 'Age population, age 24, female',
 'Age population, age 24, male',
 'Age population, age 25, female',
 'Age population, age 25, male',
 'Antiretroviral therapy coverage (% of people living with HIV)',
 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)',
 'Birth rate, crude (per 1,000 people)',
 'Births attended by skilled health staff (% of total)',
 'Capital health expenditure (% of GDP)',
 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
 'Cause of death, by injury (% of total)',
 'Cause of death, by non-communicable diseases (% of total)',
 'Cause of death, by other COVID-19 pandemic-related outcomes (% of total)',
 'Children (0-14) living with HIV',
 'Children (ages 0-14) newly infected with HIV',
 'Children orphaned by HIV/AIDS',
 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)',
 'Community health workers (per 1,000 people)',
 'Completeness of birth registration (%)',
 'Completeness of birth registration, female (%)',
 'Completeness of birth registration, male (%)',
 'Completeness of birth registration, rural (%)',
 'Completeness of birth registration, urban (%)',
 'Completeness of death registration with cause-of-death information (%)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, male (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, male (2 prevent ways and reject 3 misconceptions)',
 'Condom use at last high-risk sex, adult female (% ages 15-49)',
 'Condom use at last high-risk sex, adult male (% ages 15-49)',
 'Condom use, population ages 15-24, female (% of females ages 15-24)',
 'Condom use, population ages 15-24, male (% of males ages 15-24)',
 'Consumption of iodized salt (% of households)',
 'Contraceptive prevalence, any method (% of all women ages 15-49)',
 'Contraceptive prevalence, any method (% of married women ages 15-49)',
 'Contraceptive prevalence, any method (% of sexually active unmarried women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of all women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of married women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of sexually active unmarried women ages 15-49)',
 'Current health expenditure (% of GDP)',
 'Current health expenditure per capita (current US$)',
 'Current health expenditure per capita, PPP (current international $)',
 'Death rate, crude (per 1,000 people)',
 'Demand for family planning satisfied by any methods (% of married women with demand for family planning)',
 'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)',
 'Diabetes prevalence (% of population ages 20 to 79)',
 'Diarrhea treatment (% of children under 5 receiving oral rehydration and continued feeding)',
 'Diarrhea treatment (% of children under 5 who received ORS packet)',
 'Domestic general government health expenditure (% of GDP)',
 'Domestic general government health expenditure (% of current health expenditure)',
 'Domestic general government health expenditure (% of general government expenditure)',
 'Domestic general government health expenditure per capita (current US$)',
 'Domestic general government health expenditure per capita, PPP (current international $)',
 'Domestic private health expenditure (% of current health expenditure)',
 'Domestic private health expenditure per capita (current US$)',
 'Domestic private health expenditure per capita, PPP  (current international $)',
 'Exclusive breastfeeding (% of children under 6 months)',
 'External health expenditure (% of current health expenditure)',
 'External health expenditure channeled through government (% of external health expenditure)',
 'External health expenditure per capita (current US$)',
 'External health expenditure per capita, PPP (current international $)',
 'Female headed households (% of households with a female head)',
 'Fertility rate, total (births per woman)',
 'GNI per capita, Atlas method (current US$)',
 'Hospital beds (per 1,000 people)',
 'Human capital index (HCI) (scale 0-1)',
 'Human capital index (HCI), female (scale 0-1)',
 'Human capital index (HCI), female, lower bound (scale 0-1)',
 'Human capital index (HCI), female, upper bound (scale 0-1)',
 'Human capital index (HCI), lower bound (scale 0-1)',
 'Human capital index (HCI), male (scale 0-1)',
 'Human capital index (HCI), male, lower bound (scale 0-1)',
 'Human capital index (HCI), male, upper bound (scale 0-1)',
 'Human capital index (HCI), upper bound (scale 0-1)',
 'Immunization, BCG (% of one-year-old children)',
 'Immunization, DPT (% of children ages 12-23 months)',
 'Immunization, HepB3 (% of one-year-old children)',
 'Immunization, Hib3 (% of children ages 12-23 months)',
 'Immunization, Pol3 (% of one-year-old children)',
 'Immunization, measles (% of children ages 12-23 months)',
 'Immunization, measles second dose (% of children by the nationally recommended age)',
 'Incidence of HIV, ages 15-24 (per 1,000 uninfected population ages 15-24)',
 'Incidence of HIV, ages 15-49 (per 1,000 uninfected population ages 15-49)',
 'Incidence of HIV, ages 50+ (per 1,000 uninfected population ages 50+)',
 'Incidence of HIV, all (per 1,000 uninfected population)',
 'Incidence of malaria (per 1,000 population at risk)',
 'Incidence of tuberculosis (per 100,000 people)',
 'Infant and young child feeding practices, all 3 IYCF (% children ages 6-23 months)',
 'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)',
 'Labor force, female (% of total labor force)',
 'Labor force, total',
 'Life expectancy at birth, female (years)',
 'Life expectancy at birth, male (years)',
 'Life expectancy at birth, total (years)',
 'Lifetime risk of maternal death (%)',
 'Lifetime risk of maternal death (1 in: rate varies by country)',
 'Literacy rate, adult female (% of females ages 15 and above)',
 'Literacy rate, adult male (% of males ages 15 and above)',
 'Literacy rate, adult total (% of people ages 15 and above)',
 'Literacy rate, youth male (% of males ages 15-24)',
 'Literacy rate, youth total (% of people ages 15-24)',
 'Low-birthweight babies (% of births)',
 'Malaria cases reported',
 'Maternal leave benefits (% of wages paid in covered period)',
 'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
 'Maternal mortality ratio (national estimate, per 100,000 live births)',
 'Mortality caused by road traffic injury (per 100,000 people)',
 'Mortality caused by road traffic injury, female (per 100,000 female population)',
 'Mortality caused by road traffic injury, male (per 100,000 male population)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)',
 'Mortality rate attributed to household and ambient air pollution (per 100,000 population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)',
 'Mortality rate attributed to unintentional poisoning (per 100,000 population)',
 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, female (per 100,000 female population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, male (per 100,000 male population)',
 'Mortality rate, adult, female (per 1,000 female adults)',
 'Mortality rate, adult, male (per 1,000 male adults)',
 'Mortality rate, infant (per 1,000 live births)',
 'Mortality rate, infant, female (per 1,000 live births)',
 'Mortality rate, infant, male (per 1,000 live births)',
 'Mortality rate, neonatal (per 1,000 live births)',
 'Mortality rate, under-5 (per 1,000)',
 'Mortality rate, under-5, female (per 1,000)',
 'Mortality rate, under-5, male (per 1,000)',
 'Net migration',
 'Newborns protected against tetanus (%)',
 'Number of deaths ages 10-14 years',
 'Number of deaths ages 10-14 years, female',
 'Number of deaths ages 10-14 years, male',
 'Number of deaths ages 10-19 years',
 'Number of deaths ages 10-19 years, female',
 'Number of deaths ages 10-19 years, male',
 'Number of deaths ages 15-19 years',
 'Number of deaths ages 15-19 years, female',
 'Number of deaths ages 15-19 years, male',
 'Number of deaths ages 20-24 years',
 'Number of deaths ages 20-24 years, female',
 'Number of deaths ages 20-24 years, male',
 'Number of deaths ages 5-9 years',
 'Number of deaths ages 5-9 years, female',
 'Number of deaths ages 5-9 years, male',
 'Number of infant deaths',
 'Number of infant deaths, female',
 'Number of infant deaths, male',
 'Number of maternal deaths',
 'Number of neonatal deaths',
 'Number of people pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure',
 'Number of people pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure',
 'Number of people pushed below the 60% median consumption poverty line by out-of-pocket health care expenditure',
 'Number of people pushed further below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure',
 'Number of people pushed further below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure',
 'Number of people pushed further below the 60% median consumption poverty line by out-of-pocket health care expenditure',
 'Number of people pushed or further pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure',
 'Number of people pushed or further pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure',
 'Number of people pushed or further pushed below the 60% median consumption poverty line by out-of-pocket health care expenditure',
 'Number of people spending more than 10% of household consumption or income on out-of-pocket health care expenditure',
 'Number of people spending more than 25% of household consumption or income on out-of-pocket health care expenditure',
 'Number of people who are undernourished',
 'Number of stillbirths',
 'Number of surgical procedures (per 100,000 population)',
 'Number of under-five deaths',
 'Number of under-five deaths, female',
 'Number of under-five deaths, male',
 'Number of weeks of maternity leave',
 'Nurses and midwives (per 1,000 people)',
 'Out-of-pocket expenditure (% of current health expenditure)',
 'Out-of-pocket expenditure per capita (current US$)',
 'Out-of-pocket expenditure per capita, PPP (current international $)',
 'People practicing open defecation (% of population)',
 'People practicing open defecation, rural (% of rural population)',
 'People practicing open defecation, urban (% of urban population)',
 'People using at least basic drinking water services (% of population)',
 'People using at least basic drinking water services, rural (% of rural population)',
 'People using at least basic drinking water services, urban (% of urban population)',
 'People using at least basic sanitation services (% of population)',
 'People using at least basic sanitation services, rural (% of rural population)',
 'People using at least basic sanitation services, urban  (% of urban population)',
 'People using safely managed drinking water services (% of population)',
 'People using safely managed drinking water services, rural (% of rural population)',
 'People using safely managed drinking water services, urban (% of urban population)',
 'People using safely managed sanitation services (% of population)',
 'People using safely managed sanitation services, rural (% of rural population)',
 'People using safely managed sanitation services, urban  (% of urban population)',
 'People with basic handwashing facilities including soap and water (% of population)',
 'People with basic handwashing facilities including soap and water, rural (% of rural population)',
 'People with basic handwashing facilities including soap and water, urban (% of urban population)',
 'Physicians (per 1,000 people)',
 'Population ages 0-14 (% of total population)',
 'Population ages 0-14, female',
 'Population ages 0-14, female (% of female population)',
 'Population ages 0-14, male',
 'Population ages 0-14, male (% of male population)',
 'Population ages 00-04, female',
 'Population ages 00-04, female (% of female population)',
 'Population ages 00-04, male',
 'Population ages 00-04, male (% of male population)',
 'Population ages 00-14, total',
 'Population ages 05-09, female',
 'Population ages 05-09, female (% of female population)',
 'Population ages 05-09, male',
 'Population ages 05-09, male (% of male population)',
 'Population ages 10-14, female',
 'Population ages 10-14, female (% of female population)',
 'Population ages 10-14, male',
 'Population ages 10-14, male (% of male population)',
 'Population ages 15-19, female',
 'Population ages 15-19, female (% of female population)',
 'Population ages 15-19, male',
 'Population ages 15-19, male (% of male population)',
 'Population ages 15-64 (% of total population)',
 'Population ages 15-64, female',
 'Population ages 15-64, female (% of female population)',
 'Population ages 15-64, male',
 'Population ages 15-64, male (% of male population)',
 'Population ages 15-64, total',
 'Population ages 20-24, female',
 'Population ages 20-24, female (% of female population)',
 'Population ages 20-24, male',
 'Population ages 20-24, male (% of male population)',
 'Population ages 25-29, female',
 'Population ages 25-29, female (% of female population)',
 'Population ages 25-29, male',
 'Population ages 25-29, male (% of male population)',
 'Population ages 30-34, female',
 'Population ages 30-34, female (% of female population)',
 'Population ages 30-34, male',
 'Population ages 30-34, male (% of male population)',
 'Population ages 35-39, female',
 'Population ages 35-39, female (% of female population)',
 'Population ages 35-39, male',
 'Population ages 35-39, male (% of male population)',
 'Population ages 40-44, female',
 'Population ages 40-44, female (% of female population)',
 'Population ages 40-44, male',
 'Population ages 40-44, male (% of male population)',
 'Population ages 45-49, female',
 'Population ages 45-49, female (% of female population)',
 'Population ages 45-49, male',
 'Population ages 45-49, male (% of male population)',
 'Population ages 50-54, female',
 'Population ages 50-54, female (% of female population)',
 'Population ages 50-54, male',
 'Population ages 50-54, male (% of male population)',
 'Population ages 55-59, female',
 'Population ages 55-59, female (% of female population)',
 'Population ages 55-59, male',
 'Population ages 55-59, male (% of male population)',
 'Population ages 60-64, female',
 'Population ages 60-64, female (% of female population)',
 'Population ages 60-64, male',
 'Population ages 60-64, male (% of male population)',
 'Population ages 65 and above (% of total population)',
 'Population ages 65 and above, female',
 'Population ages 65 and above, female (% of female population)',
 'Population ages 65 and above, male',
 'Population ages 65 and above, male (% of male population)',
 'Population ages 65 and above, total',
 'Population ages 65-69, female',
 'Population ages 65-69, female (% of female population)',
 'Population ages 65-69, male',
 'Population ages 65-69, male (% of male population)',
 'Population ages 70-74, female',
 'Population ages 70-74, female (% of female population)',
 'Population ages 70-74, male',
 'Population ages 70-74, male (% of male population)',
 'Population ages 75-79, female',
 'Population ages 75-79, female (% of female population)',
 'Population ages 75-79, male',
 'Population ages 75-79, male (% of male population)',
 'Population ages 80 and above, female',
 'Population ages 80 and above, male',
 'Population ages 80 and above, male (% of male population)',
 'Population ages 80 and older, female (% of female population)',
 'Population growth (annual %)',
 'Population, female',
 'Population, female (% of total population)',
 'Population, male',
 'Population, male (% of total population)',
 'Population, total',
 'Postnatal care coverage (% mothers)',
 'Poverty headcount ratio at national poverty line (% of population)',
 'Pregnant women receiving prenatal care (%)',
 'Pregnant women receiving prenatal care of at least four visits (% of pregnant women)',
 'Prevalence of HIV, female (% ages 15-24)',
 'Prevalence of HIV, male (% ages 15-24)',
 'Prevalence of HIV, total (% of population ages 15-49)',
 'Prevalence of anemia among children (% of children ages 6-59 months)',
 'Prevalence of anemia among non-pregnant women (% of women ages 15-49)',
 'Prevalence of anemia among pregnant women (%)',
 'Prevalence of anemia among women of reproductive age (% of women ages 15-49)',
 'Prevalence of current tobacco use (% of adults)',
 'Prevalence of current tobacco use, females (% of female adults)',

In [16]:
df_long = df.melt(
    id_vars=["Series Name", "Series Code", "Country Name", "Country Code"],
    value_vars=year_cols,
    var_name="Year",
    value_name="Value"
)

In [17]:
df_long["Year"] = df_long["Year"].str.extract(r"(\d{4})").astype(int)

In [18]:
df_long.head()

,Series Name,Series Code,Country Name,Country Code,Year,Value
0,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,Afghanistan,AFG,1960,140.598
1,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,Burkina Faso,BFA,1960,135.470
2,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,Burundi,BDI,1960,95.936
3,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,Central African Republic,CAF,1960,169.818
4,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,Chad,TCD,1960,195.419

In [43]:
df_long.shape

(771875, 6)

In [19]:
df_long["Value"].isna().sum()

np.int64(354872)

In [20]:
df_long = df_long.dropna(subset=["Value"])

In [21]:
df_long.shape

(417003, 6)

In [23]:
df_long["Series Name"].nunique()

462

In [24]:
sorted(df_long["Series Name"].unique())

['AIDS estimated deaths (UNAIDS estimates)',
 'ARI treatment (% of children under 5 taken to a health provider)',
 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
 'Adults (ages 15+) and children (0-14 years) living with HIV',
 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV',
 'Adults (ages 15+) living with HIV',
 'Adults (ages 15-49) newly infected with HIV',
 'Age at first marriage, female',
 'Age at first marriage, male',
 'Age dependency ratio (% of working-age population)',
 'Age dependency ratio, old',
 'Age dependency ratio, young',
 'Age population, age 00, female',
 'Age population, age 00, male',
 'Age population, age 01, female',
 'Age population, age 01, male',
 'Age population, age 02, female',
 'Age population, age 02, male',
 'Age population, age 03, female',
 'Age population, age 03, male',
 'Age population, age 04, female',
 'Age population, age 04, male',
 'Age population, age 05, female',
 'Age population, age 05, male',
 'Age population, age 06, female',
 'Age population, age 06, male',
 'Age population, age 07, female',
 'Age population, age 07, male',
 'Age population, age 08, female',
 'Age population, age 08, male',
 'Age population, age 09, female',
 'Age population, age 09, male',
 'Age population, age 10, female',
 'Age population, age 10, male',
 'Age population, age 11, female',
 'Age population, age 11, male',
 'Age population, age 12, female',
 'Age population, age 12, male',
 'Age population, age 13, female',
 'Age population, age 13, male',
 'Age population, age 14, female',
 'Age population, age 14, male',
 'Age population, age 15, female',
 'Age population, age 15, male',
 'Age population, age 16, female',
 'Age population, age 16, male',
 'Age population, age 17, female',
 'Age population, age 17, male',
 'Age population, age 18, female',
 'Age population, age 18, male',
 'Age population, age 19, female',
 'Age population, age 19, male',
 'Age population, age 20, female',
 'Age population, age 20, male',
 'Age population, age 21, female',
 'Age population, age 21, male',
 'Age population, age 22, female',
 'Age population, age 22, male',
 'Age population, age 23, female',
 'Age population, age 23, male',
 'Age population, age 24, female',
 'Age population, age 24, male',
 'Age population, age 25, female',
 'Age population, age 25, male',
 'Antiretroviral therapy coverage (% of people living with HIV)',
 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)',
 'Birth rate, crude (per 1,000 people)',
 'Births attended by skilled health staff (% of total)',
 'Capital health expenditure (% of GDP)',
 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
 'Cause of death, by injury (% of total)',
 'Cause of death, by non-communicable diseases (% of total)',
 'Cause of death, by other COVID-19 pandemic-related outcomes (% of total)',
 'Children (0-14) living with HIV',
 'Children (ages 0-14) newly infected with HIV',
 'Children orphaned by HIV/AIDS',
 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)',
 'Community health workers (per 1,000 people)',
 'Completeness of birth registration (%)',
 'Completeness of birth registration, female (%)',
 'Completeness of birth registration, male (%)',
 'Completeness of birth registration, rural (%)',
 'Completeness of birth registration, urban (%)',
 'Completeness of death registration with cause-of-death information (%)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, male (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, male (2 prevent ways and reject 3 misconceptions)',
 'Condom use at last high-risk sex, adult female (% ages 15-49)',
 'Condom use at last high-risk sex, adult male (% ages 15-49)',
 'Condom use, population ages 15-24, female (% of females ages 15-24)',
 'Condom use, population ages 15-24, male (% of males ages 15-24)',
 'Consumption of iodized salt (% of households)',
 'Contraceptive prevalence, any method (% of all women ages 15-49)',
 'Contraceptive prevalence, any method (% of married women ages 15-49)',
 'Contraceptive prevalence, any method (% of sexually active unmarried women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of all women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of married women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of sexually active unmarried women ages 15-49)',
 'Current health expenditure (% of GDP)',
 'Current health expenditure per capita (current US$)',
 'Current health expenditure per capita, PPP (current international $)',
 'Death rate, crude (per 1,000 people)',
 'Demand for family planning satisfied by any methods (% of married women with demand for family planning)',
 'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)',
 'Diabetes prevalence (% of population ages 20 to 79)',
 'Diarrhea treatment (% of children under 5 receiving oral rehydration and continued feeding)',
 'Diarrhea treatment (% of children under 5 who received ORS packet)',
 'Domestic general government health expenditure (% of GDP)',
 'Domestic general government health expenditure (% of current health expenditure)',
 'Domestic general government health expenditure (% of general government expenditure)',
 'Domestic general government health expenditure per capita (current US$)',
 'Domestic general government health expenditure per capita, PPP (current international $)',
 'Domestic private health expenditure (% of current health expenditure)',
 'Domestic private health expenditure per capita (current US$)',
 'Domestic private health expenditure per capita, PPP  (current international $)',
 'Exclusive breastfeeding (% of children under 6 months)',
 'External health expenditure (% of current health expenditure)',
 'External health expenditure channeled through government (% of external health expenditure)',
 'External health expenditure per capita (current US$)',
 'External health expenditure per capita, PPP (current international $)',
 'Female headed households (% of households with a female head)',
 'Fertility rate, total (births per woman)',
 'GNI per capita, Atlas method (current US$)',
 'Hospital beds (per 1,000 people)',
 'Human capital index (HCI) (scale 0-1)',
 'Human capital index (HCI), female (scale 0-1)',
 'Human capital index (HCI), female, lower bound (scale 0-1)',
 'Human capital index (HCI), female, upper bound (scale 0-1)',
 'Human capital index (HCI), lower bound (scale 0-1)',
 'Human capital index (HCI), male (scale 0-1)',
 'Human capital index (HCI), male, lower bound (scale 0-1)',
 'Human capital index (HCI), male, upper bound (scale 0-1)',
 'Human capital index (HCI), upper bound (scale 0-1)',
 'Immunization, BCG (% of one-year-old children)',
 'Immunization, DPT (% of children ages 12-23 months)',
 'Immunization, HepB3 (% of one-year-old children)',
 'Immunization, Hib3 (% of children ages 12-23 months)',
 'Immunization, Pol3 (% of one-year-old children)',
 'Immunization, measles (% of children ages 12-23 months)',
 'Immunization, measles second dose (% of children by the nationally recommended age)',
 'Incidence of HIV, ages 15-24 (per 1,000 uninfected population ages 15-24)',
 'Incidence of HIV, ages 15-49 (per 1,000 uninfected population ages 15-49)',
 'Incidence of HIV, ages 50+ (per 1,000 uninfected population ages 50+)',
 'Incidence of HIV, all (per 1,000 uninfected population)',
 'Incidence of malaria (per 1,000 population at risk)',
 'Incidence of tuberculosis (per 100,000 people)',
 'Infant and young child feeding practices, all 3 IYCF (% children ages 6-23 months)',
 'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)',
 'Labor force, female (% of total labor force)',
 'Labor force, total',
 'Life expectancy at birth, female (years)',
 'Life expectancy at birth, male (years)',
 'Life expectancy at birth, total (years)',
 'Lifetime risk of maternal death (%)',
 'Lifetime risk of maternal death (1 in: rate varies by country)',
 'Literacy rate, adult female (% of females ages 15 and above)',
 'Literacy rate, adult male (% of males ages 15 and above)',
 'Literacy rate, adult total (% of people ages 15 and above)',
 'Literacy rate, youth male (% of males ages 15-24)',
 'Literacy rate, youth total (% of people ages 15-24)',
 'Low-birthweight babies (% of births)',
 'Malaria cases reported',
 'Maternal leave benefits (% of wages paid in covered period)',
 'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
 'Maternal mortality ratio (national estimate, per 100,000 live births)',
 'Mortality caused by road traffic injury (per 100,000 people)',
 'Mortality caused by road traffic injury, female (per 100,000 female population)',
 'Mortality caused by road traffic injury, male (per 100,000 male population)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)',
 'Mortality rate attributed to household and ambient air pollution (per 100,000 population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)',
 'Mortality rate attributed to unintentional poisoning (per 100,000 population)',
 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, female (per 100,000 female population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, male (per 100,000 male population)',
 'Mortality rate, adult, female (per 1,000 female adults)',
 'Mortality rate, adult, male (per 1,000 male adults)',
 'Mortality rate, infant (per 1,000 live births)',
 'Mortality rate, infant, female (per 1,000 live births)',
 'Mortality rate, infant, male (per 1,000 live births)',
 'Mortality rate, neonatal (per 1,000 live births)',
 'Mortality rate, under-5 (per 1,000)',
 'Mortality rate, under-5, female (per 1,000)',
 'Mortality rate, under-5, male (per 1,000)',
 'Net migration',
 'Newborns protected against tetanus (%)',
 'Number of deaths ages 10-14 years',
 'Number of deaths ages 10-14 years, female',
 'Number of deaths ages 10-14 years, male',
 'Number of deaths ages 10-19 years',
 'Number of deaths ages 10-19 years, female',
 'Number of deaths ages 10-19 years, male',
 'Number of deaths ages 15-19 years',
 'Number of deaths ages 15-19 years, female',
 'Number of deaths ages 15-19 years, male',
 'Number of deaths ages 20-24 years',
 'Number of deaths ages 20-24 years, female',
 'Number of deaths ages 20-24 years, male',
 'Number of deaths ages 5-9 years',
 'Number of deaths ages 5-9 years, female',
 'Number of deaths ages 5-9 years, male',
 'Number of infant deaths',
 'Number of infant deaths, female',
 'Number of infant deaths, male',
 'Number of maternal deaths',
 'Number of neonatal deaths',
 'Number of people who are undernourished',
 'Number of stillbirths',
 'Number of surgical procedures (per 100,000 population)',
 'Number of under-five deaths',
 'Number of under-five deaths, female',
 'Number of under-five deaths, male',
 'Number of weeks of maternity leave',
 'Nurses and midwives (per 1,000 people)',
 'Out-of-pocket expenditure (% of current health expenditure)',
 'Out-of-pocket expenditure per capita (current US$)',
 'Out-of-pocket expenditure per capita, PPP (current international $)',
 'People practicing open defecation (% of population)',
 'People practicing open defecation, rural (% of rural population)',
 'People practicing open defecation, urban (% of urban population)',
 'People using at least basic drinking water services (% of population)',
 'People using at least basic drinking water services, rural (% of rural population)',
 'People using at least basic drinking water services, urban (% of urban population)',
 'People using at least basic sanitation services (% of population)',
 'People using at least basic sanitation services, rural (% of rural population)',
 'People using at least basic sanitation services, urban  (% of urban population)',
 'People using safely managed drinking water services (% of population)',
 'People using safely managed drinking water services, rural (% of rural population)',
 'People using safely managed drinking water services, urban (% of urban population)',
 'People using safely managed sanitation services (% of population)',
 'People using safely managed sanitation services, rural (% of rural population)',
 'People using safely managed sanitation services, urban  (% of urban population)',
 'People with basic handwashing facilities including soap and water (% of population)',
 'People with basic handwashing facilities including soap and water, rural (% of rural population)',
 'People with basic handwashing facilities including soap and water, urban (% of urban population)',
 'Physicians (per 1,000 people)',
 'Population ages 0-14 (% of total population)',
 'Population ages 0-14, female',
 'Population ages 0-14, female (% of female population)',
 'Population ages 0-14, male',
 'Population ages 0-14, male (% of male population)',
 'Population ages 00-04, female',
 'Population ages 00-04, female (% of female population)',
 'Population ages 00-04, male',
 'Population ages 00-04, male (% of male population)',
 'Population ages 00-14, total',
 'Population ages 05-09, female',
 'Population ages 05-09, female (% of female population)',
 'Population ages 05-09, male',
 'Population ages 05-09, male (% of male population)',
 'Population ages 10-14, female',
 'Population ages 10-14, female (% of female population)',
 'Population ages 10-14, male',
 'Population ages 10-14, male (% of male population)',
 'Population ages 15-19, female',
 'Population ages 15-19, female (% of female population)',
 'Population ages 15-19, male',
 'Population ages 15-19, male (% of male population)',
 'Population ages 15-64 (% of total population)',
 'Population ages 15-64, female',
 'Population ages 15-64, female (% of female population)',
 'Population ages 15-64, male',
 'Population ages 15-64, male (% of male population)',
 'Population ages 15-64, total',
 'Population ages 20-24, female',
 'Population ages 20-24, female (% of female population)',
 'Population ages 20-24, male',
 'Population ages 20-24, male (% of male population)',
 'Population ages 25-29, female',
 'Population ages 25-29, female (% of female population)',
 'Population ages 25-29, male',
 'Population ages 25-29, male (% of male population)',
 'Population ages 30-34, female',
 'Population ages 30-34, female (% of female population)',
 'Population ages 30-34, male',
 'Population ages 30-34, male (% of male population)',
 'Population ages 35-39, female',
 'Population ages 35-39, female (% of female population)',
 'Population ages 35-39, male',
 'Population ages 35-39, male (% of male population)',
 'Population ages 40-44, female',
 'Population ages 40-44, female (% of female population)',
 'Population ages 40-44, male',
 'Population ages 40-44, male (% of male population)',
 'Population ages 45-49, female',
 'Population ages 45-49, female (% of female population)',
 'Population ages 45-49, male',
 'Population ages 45-49, male (% of male population)',
 'Population ages 50-54, female',
 'Population ages 50-54, female (% of female population)',
 'Population ages 50-54, male',
 'Population ages 50-54, male (% of male population)',
 'Population ages 55-59, female',
 'Population ages 55-59, female (% of female population)',
 'Population ages 55-59, male',
 'Population ages 55-59, male (% of male population)',
 'Population ages 60-64, female',
 'Population ages 60-64, female (% of female population)',
 'Population ages 60-64, male',
 'Population ages 60-64, male (% of male population)',
 'Population ages 65 and above (% of total population)',
 'Population ages 65 and above, female',
 'Population ages 65 and above, female (% of female population)',
 'Population ages 65 and above, male',
 'Population ages 65 and above, male (% of male population)',
 'Population ages 65 and above, total',
 'Population ages 65-69, female',
 'Population ages 65-69, female (% of female population)',
 'Population ages 65-69, male',
 'Population ages 65-69, male (% of male population)',
 'Population ages 70-74, female',
 'Population ages 70-74, female (% of female population)',
 'Population ages 70-74, male',
 'Population ages 70-74, male (% of male population)',
 'Population ages 75-79, female',
 'Population ages 75-79, female (% of female population)',
 'Population ages 75-79, male',
 'Population ages 75-79, male (% of male population)',
 'Population ages 80 and above, female',
 'Population ages 80 and above, male',
 'Population ages 80 and above, male (% of male population)',
 'Population ages 80 and older, female (% of female population)',
 'Population growth (annual %)',
 'Population, female',
 'Population, female (% of total population)',
 'Population, male',
 'Population, male (% of total population)',
 'Population, total',
 'Postnatal care coverage (% mothers)',
 'Poverty headcount ratio at national poverty line (% of population)',
 'Pregnant women receiving prenatal care (%)',
 'Pregnant women receiving prenatal care of at least four visits (% of pregnant women)',
 'Prevalence of HIV, female (% ages 15-24)',
 'Prevalence of HIV, male (% ages 15-24)',
 'Prevalence of HIV, total (% of population ages 15-49)',
 'Prevalence of anemia among children (% of children ages 6-59 months)',
 'Prevalence of anemia among non-pregnant women (% of women ages 15-49)',
 'Prevalence of anemia among pregnant women (%)',
 'Prevalence of anemia among women of reproductive age (% of women ages 15-49)',
 'Prevalence of current tobacco use (% of adults)',
 'Prevalence of current tobacco use, females (% of female adults)',
 'Prevalence of current tobacco use, males (% of male adults)',
 'Prevalence of hypertension (% of adults ages 30-79)',
 'Prevalence of hypertension, female (% of female adults ages 30-79)',
 'Prevalence of hypertension, male (% of male adults ages 30-79)',
 'Prevalence of overweight (% of adults)',
 'Prevalence of overweight (% of children under 5)',
 'Prevalence of overweight (modeled estimate, % of children under 5)',
 'Prevalence of overweight, female (% of children under 5)',
 'Prevalence of overweight, female (% of female adults)',
 'Prevalence of overweight, female (modeled estimate, % of children under 5)',
 'Prevalence of overweight, male (% of children under 5)',
 'Prevalence of overweight, male (% of male adults)',
 'Prevalence of overweight, male (modeled estimate, % of children under 5)',
 'Prevalence of severe wasting, weight for height (% of children under 5)',
 'Prevalence of severe wasting, weight for height, female (% of children under 5)',
 'Prevalence of severe wasting, weight for height, male (% of children under 5)',
 'Prevalence of stunting, height for age (% of children under 5)',
 'Prevalence of stunting, height for age (modeled estimate, % of children under 5)',
 'Prevalence of stunting, height for age, female (% of children under 5)',

In [25]:
df_long["Country Name"].nunique()

25

In [26]:
df_long["Year"].min(), df_long["Year"].max()

(np.int64(1960), np.int64(2024))

In [53]:
df_long["Value"].describe()

count    4.170030e+05
mean     3.314844e+05
std      1.869196e+06
min     -2.081303e+06
25%      1.270000e+01
50%      1.256000e+02
75%      8.699425e+04
max      1.092763e+08
Name: Value, dtype: float64

In [54]:
df_long["Series Name"].nunique()

462

In [55]:
sorted(df_long["Series Name"].unique())

['AIDS estimated deaths (UNAIDS estimates)',
 'ARI treatment (% of children under 5 taken to a health provider)',
 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
 'Adults (ages 15+) and children (0-14 years) living with HIV',
 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV',
 'Adults (ages 15+) living with HIV',
 'Adults (ages 15-49) newly infected with HIV',
 'Age at first marriage, female',
 'Age at first marriage, male',
 'Age dependency ratio (% of working-age population)',
 'Age dependency ratio, old',
 'Age dependency ratio, young',
 'Age population, age 00, female',
 'Age population, age 00, male',
 'Age population, age 01, female',
 'Age population, age 01, male',
 'Age population, age 02, female',
 'Age population, age 02, male',
 'Age population, age 03, female',
 'Age population, age 03, male',
 'Age population, age 04, female',
 'Age population, age 04, male',
 'Age population, age 05, female',
 'Age population, age 05, male',
 'Age population, age 06, female',
 'Age population, age 06, male',
 'Age population, age 07, female',
 'Age population, age 07, male',
 'Age population, age 08, female',
 'Age population, age 08, male',
 'Age population, age 09, female',
 'Age population, age 09, male',
 'Age population, age 10, female',
 'Age population, age 10, male',
 'Age population, age 11, female',
 'Age population, age 11, male',
 'Age population, age 12, female',
 'Age population, age 12, male',
 'Age population, age 13, female',
 'Age population, age 13, male',
 'Age population, age 14, female',
 'Age population, age 14, male',
 'Age population, age 15, female',
 'Age population, age 15, male',
 'Age population, age 16, female',
 'Age population, age 16, male',
 'Age population, age 17, female',
 'Age population, age 17, male',
 'Age population, age 18, female',
 'Age population, age 18, male',
 'Age population, age 19, female',
 'Age population, age 19, male',
 'Age population, age 20, female',
 'Age population, age 20, male',
 'Age population, age 21, female',
 'Age population, age 21, male',
 'Age population, age 22, female',
 'Age population, age 22, male',
 'Age population, age 23, female',
 'Age population, age 23, male',
 'Age population, age 24, female',
 'Age population, age 24, male',
 'Age population, age 25, female',
 'Age population, age 25, male',
 'Antiretroviral therapy coverage (% of people living with HIV)',
 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)',
 'Birth rate, crude (per 1,000 people)',
 'Births attended by skilled health staff (% of total)',
 'Capital health expenditure (% of GDP)',
 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
 'Cause of death, by injury (% of total)',
 'Cause of death, by non-communicable diseases (% of total)',
 'Cause of death, by other COVID-19 pandemic-related outcomes (% of total)',
 'Children (0-14) living with HIV',
 'Children (ages 0-14) newly infected with HIV',
 'Children orphaned by HIV/AIDS',
 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)',
 'Community health workers (per 1,000 people)',
 'Completeness of birth registration (%)',
 'Completeness of birth registration, female (%)',
 'Completeness of birth registration, male (%)',
 'Completeness of birth registration, rural (%)',
 'Completeness of birth registration, urban (%)',
 'Completeness of death registration with cause-of-death information (%)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, male (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, male (2 prevent ways and reject 3 misconceptions)',
 'Condom use at last high-risk sex, adult female (% ages 15-49)',
 'Condom use at last high-risk sex, adult male (% ages 15-49)',
 'Condom use, population ages 15-24, female (% of females ages 15-24)',
 'Condom use, population ages 15-24, male (% of males ages 15-24)',
 'Consumption of iodized salt (% of households)',
 'Contraceptive prevalence, any method (% of all women ages 15-49)',
 'Contraceptive prevalence, any method (% of married women ages 15-49)',
 'Contraceptive prevalence, any method (% of sexually active unmarried women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of all women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of married women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of sexually active unmarried women ages 15-49)',
 'Current health expenditure (% of GDP)',
 'Current health expenditure per capita (current US$)',
 'Current health expenditure per capita, PPP (current international $)',
 'Death rate, crude (per 1,000 people)',
 'Demand for family planning satisfied by any methods (% of married women with demand for family planning)',
 'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)',
 'Diabetes prevalence (% of population ages 20 to 79)',
 'Diarrhea treatment (% of children under 5 receiving oral rehydration and continued feeding)',
 'Diarrhea treatment (% of children under 5 who received ORS packet)',
 'Domestic general government health expenditure (% of GDP)',
 'Domestic general government health expenditure (% of current health expenditure)',
 'Domestic general government health expenditure (% of general government expenditure)',
 'Domestic general government health expenditure per capita (current US$)',
 'Domestic general government health expenditure per capita, PPP (current international $)',
 'Domestic private health expenditure (% of current health expenditure)',
 'Domestic private health expenditure per capita (current US$)',
 'Domestic private health expenditure per capita, PPP  (current international $)',
 'Exclusive breastfeeding (% of children under 6 months)',
 'External health expenditure (% of current health expenditure)',
 'External health expenditure channeled through government (% of external health expenditure)',
 'External health expenditure per capita (current US$)',
 'External health expenditure per capita, PPP (current international $)',
 'Female headed households (% of households with a female head)',
 'Fertility rate, total (births per woman)',
 'GNI per capita, Atlas method (current US$)',
 'Hospital beds (per 1,000 people)',
 'Human capital index (HCI) (scale 0-1)',
 'Human capital index (HCI), female (scale 0-1)',
 'Human capital index (HCI), female, lower bound (scale 0-1)',
 'Human capital index (HCI), female, upper bound (scale 0-1)',
 'Human capital index (HCI), lower bound (scale 0-1)',
 'Human capital index (HCI), male (scale 0-1)',
 'Human capital index (HCI), male, lower bound (scale 0-1)',
 'Human capital index (HCI), male, upper bound (scale 0-1)',
 'Human capital index (HCI), upper bound (scale 0-1)',
 'Immunization, BCG (% of one-year-old children)',
 'Immunization, DPT (% of children ages 12-23 months)',
 'Immunization, HepB3 (% of one-year-old children)',
 'Immunization, Hib3 (% of children ages 12-23 months)',
 'Immunization, Pol3 (% of one-year-old children)',
 'Immunization, measles (% of children ages 12-23 months)',
 'Immunization, measles second dose (% of children by the nationally recommended age)',
 'Incidence of HIV, ages 15-24 (per 1,000 uninfected population ages 15-24)',
 'Incidence of HIV, ages 15-49 (per 1,000 uninfected population ages 15-49)',
 'Incidence of HIV, ages 50+ (per 1,000 uninfected population ages 50+)',
 'Incidence of HIV, all (per 1,000 uninfected population)',
 'Incidence of malaria (per 1,000 population at risk)',
 'Incidence of tuberculosis (per 100,000 people)',
 'Infant and young child feeding practices, all 3 IYCF (% children ages 6-23 months)',
 'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)',
 'Labor force, female (% of total labor force)',
 'Labor force, total',
 'Life expectancy at birth, female (years)',
 'Life expectancy at birth, male (years)',
 'Life expectancy at birth, total (years)',
 'Lifetime risk of maternal death (%)',
 'Lifetime risk of maternal death (1 in: rate varies by country)',
 'Literacy rate, adult female (% of females ages 15 and above)',
 'Literacy rate, adult male (% of males ages 15 and above)',
 'Literacy rate, adult total (% of people ages 15 and above)',
 'Literacy rate, youth male (% of males ages 15-24)',
 'Literacy rate, youth total (% of people ages 15-24)',
 'Low-birthweight babies (% of births)',
 'Malaria cases reported',
 'Maternal leave benefits (% of wages paid in covered period)',
 'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
 'Maternal mortality ratio (national estimate, per 100,000 live births)',
 'Mortality caused by road traffic injury (per 100,000 people)',
 'Mortality caused by road traffic injury, female (per 100,000 female population)',
 'Mortality caused by road traffic injury, male (per 100,000 male population)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)',
 'Mortality rate attributed to household and ambient air pollution (per 100,000 population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)',
 'Mortality rate attributed to unintentional poisoning (per 100,000 population)',
 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, female (per 100,000 female population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, male (per 100,000 male population)',
 'Mortality rate, adult, female (per 1,000 female adults)',
 'Mortality rate, adult, male (per 1,000 male adults)',
 'Mortality rate, infant (per 1,000 live births)',
 'Mortality rate, infant, female (per 1,000 live births)',
 'Mortality rate, infant, male (per 1,000 live births)',
 'Mortality rate, neonatal (per 1,000 live births)',
 'Mortality rate, under-5 (per 1,000)',
 'Mortality rate, under-5, female (per 1,000)',
 'Mortality rate, under-5, male (per 1,000)',
 'Net migration',
 'Newborns protected against tetanus (%)',
 'Number of deaths ages 10-14 years',
 'Number of deaths ages 10-14 years, female',
 'Number of deaths ages 10-14 years, male',
 'Number of deaths ages 10-19 years',
 'Number of deaths ages 10-19 years, female',
 'Number of deaths ages 10-19 years, male',
 'Number of deaths ages 15-19 years',
 'Number of deaths ages 15-19 years, female',
 'Number of deaths ages 15-19 years, male',
 'Number of deaths ages 20-24 years',
 'Number of deaths ages 20-24 years, female',
 'Number of deaths ages 20-24 years, male',
 'Number of deaths ages 5-9 years',
 'Number of deaths ages 5-9 years, female',
 'Number of deaths ages 5-9 years, male',
 'Number of infant deaths',
 'Number of infant deaths, female',
 'Number of infant deaths, male',
 'Number of maternal deaths',
 'Number of neonatal deaths',
 'Number of people who are undernourished',
 'Number of stillbirths',
 'Number of surgical procedures (per 100,000 population)',
 'Number of under-five deaths',
 'Number of under-five deaths, female',
 'Number of under-five deaths, male',
 'Number of weeks of maternity leave',
 'Nurses and midwives (per 1,000 people)',
 'Out-of-pocket expenditure (% of current health expenditure)',
 'Out-of-pocket expenditure per capita (current US$)',
 'Out-of-pocket expenditure per capita, PPP (current international $)',
 'People practicing open defecation (% of population)',
 'People practicing open defecation, rural (% of rural population)',
 'People practicing open defecation, urban (% of urban population)',
 'People using at least basic drinking water services (% of population)',
 'People using at least basic drinking water services, rural (% of rural population)',
 'People using at least basic drinking water services, urban (% of urban population)',
 'People using at least basic sanitation services (% of population)',
 'People using at least basic sanitation services, rural (% of rural population)',
 'People using at least basic sanitation services, urban  (% of urban population)',
 'People using safely managed drinking water services (% of population)',
 'People using safely managed drinking water services, rural (% of rural population)',
 'People using safely managed drinking water services, urban (% of urban population)',
 'People using safely managed sanitation services (% of population)',
 'People using safely managed sanitation services, rural (% of rural population)',
 'People using safely managed sanitation services, urban  (% of urban population)',
 'People with basic handwashing facilities including soap and water (% of population)',
 'People with basic handwashing facilities including soap and water, rural (% of rural population)',
 'People with basic handwashing facilities including soap and water, urban (% of urban population)',
 'Physicians (per 1,000 people)',
 'Population ages 0-14 (% of total population)',
 'Population ages 0-14, female',
 'Population ages 0-14, female (% of female population)',
 'Population ages 0-14, male',
 'Population ages 0-14, male (% of male population)',
 'Population ages 00-04, female',
 'Population ages 00-04, female (% of female population)',
 'Population ages 00-04, male',
 'Population ages 00-04, male (% of male population)',
 'Population ages 00-14, total',
 'Population ages 05-09, female',
 'Population ages 05-09, female (% of female population)',
 'Population ages 05-09, male',
 'Population ages 05-09, male (% of male population)',
 'Population ages 10-14, female',
 'Population ages 10-14, female (% of female population)',
 'Population ages 10-14, male',
 'Population ages 10-14, male (% of male population)',
 'Population ages 15-19, female',
 'Population ages 15-19, female (% of female population)',
 'Population ages 15-19, male',
 'Population ages 15-19, male (% of male population)',
 'Population ages 15-64 (% of total population)',
 'Population ages 15-64, female',
 'Population ages 15-64, female (% of female population)',
 'Population ages 15-64, male',
 'Population ages 15-64, male (% of male population)',
 'Population ages 15-64, total',
 'Population ages 20-24, female',
 'Population ages 20-24, female (% of female population)',
 'Population ages 20-24, male',
 'Population ages 20-24, male (% of male population)',
 'Population ages 25-29, female',
 'Population ages 25-29, female (% of female population)',
 'Population ages 25-29, male',
 'Population ages 25-29, male (% of male population)',
 'Population ages 30-34, female',
 'Population ages 30-34, female (% of female population)',
 'Population ages 30-34, male',
 'Population ages 30-34, male (% of male population)',
 'Population ages 35-39, female',
 'Population ages 35-39, female (% of female population)',
 'Population ages 35-39, male',
 'Population ages 35-39, male (% of male population)',
 'Population ages 40-44, female',
 'Population ages 40-44, female (% of female population)',
 'Population ages 40-44, male',
 'Population ages 40-44, male (% of male population)',
 'Population ages 45-49, female',
 'Population ages 45-49, female (% of female population)',
 'Population ages 45-49, male',
 'Population ages 45-49, male (% of male population)',
 'Population ages 50-54, female',
 'Population ages 50-54, female (% of female population)',
 'Population ages 50-54, male',
 'Population ages 50-54, male (% of male population)',
 'Population ages 55-59, female',
 'Population ages 55-59, female (% of female population)',
 'Population ages 55-59, male',
 'Population ages 55-59, male (% of male population)',
 'Population ages 60-64, female',
 'Population ages 60-64, female (% of female population)',
 'Population ages 60-64, male',
 'Population ages 60-64, male (% of male population)',
 'Population ages 65 and above (% of total population)',
 'Population ages 65 and above, female',
 'Population ages 65 and above, female (% of female population)',
 'Population ages 65 and above, male',
 'Population ages 65 and above, male (% of male population)',
 'Population ages 65 and above, total',
 'Population ages 65-69, female',
 'Population ages 65-69, female (% of female population)',
 'Population ages 65-69, male',
 'Population ages 65-69, male (% of male population)',
 'Population ages 70-74, female',
 'Population ages 70-74, female (% of female population)',
 'Population ages 70-74, male',
 'Population ages 70-74, male (% of male population)',
 'Population ages 75-79, female',
 'Population ages 75-79, female (% of female population)',
 'Population ages 75-79, male',
 'Population ages 75-79, male (% of male population)',
 'Population ages 80 and above, female',
 'Population ages 80 and above, male',
 'Population ages 80 and above, male (% of male population)',
 'Population ages 80 and older, female (% of female population)',
 'Population growth (annual %)',
 'Population, female',
 'Population, female (% of total population)',
 'Population, male',
 'Population, male (% of total population)',
 'Population, total',
 'Postnatal care coverage (% mothers)',
 'Poverty headcount ratio at national poverty line (% of population)',
 'Pregnant women receiving prenatal care (%)',
 'Pregnant women receiving prenatal care of at least four visits (% of pregnant women)',
 'Prevalence of HIV, female (% ages 15-24)',
 'Prevalence of HIV, male (% ages 15-24)',
 'Prevalence of HIV, total (% of population ages 15-49)',
 'Prevalence of anemia among children (% of children ages 6-59 months)',
 'Prevalence of anemia among non-pregnant women (% of women ages 15-49)',
 'Prevalence of anemia among pregnant women (%)',
 'Prevalence of anemia among women of reproductive age (% of women ages 15-49)',
 'Prevalence of current tobacco use (% of adults)',
 'Prevalence of current tobacco use, females (% of female adults)',
 'Prevalence of current tobacco use, males (% of male adults)',
 'Prevalence of hypertension (% of adults ages 30-79)',
 'Prevalence of hypertension, female (% of female adults ages 30-79)',
 'Prevalence of hypertension, male (% of male adults ages 30-79)',
 'Prevalence of overweight (% of adults)',
 'Prevalence of overweight (% of children under 5)',
 'Prevalence of overweight (modeled estimate, % of children under 5)',
 'Prevalence of overweight, female (% of children under 5)',
 'Prevalence of overweight, female (% of female adults)',
 'Prevalence of overweight, female (modeled estimate, % of children under 5)',
 'Prevalence of overweight, male (% of children under 5)',
 'Prevalence of overweight, male (% of male adults)',
 'Prevalence of overweight, male (modeled estimate, % of children under 5)',
 'Prevalence of severe wasting, weight for height (% of children under 5)',
 'Prevalence of severe wasting, weight for height, female (% of children under 5)',
 'Prevalence of severe wasting, weight for height, male (% of children under 5)',
 'Prevalence of stunting, height for age (% of children under 5)',
 'Prevalence of stunting, height for age (modeled estimate, % of children under 5)',
 'Prevalence of stunting, height for age, female (% of children under 5)',

In [27]:
df_long["Series Name"].value_counts()

Series Name
Adolescent fertility rate (births per 1,000 women ages 15-19)                                                           1625
Age dependency ratio (% of working-age population)                                                                      1625
Age dependency ratio, old                                                                                               1625
Age dependency ratio, young                                                                                             1625
Age population, age 00, female                                                                                          1625
                                                                                                                        ...
Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, male (per 100,000 male population)      25
Number of weeks of maternity leave                                                                                        24
Maternal mortality ratio (national estimate, per 100,000 live births)                                                     20
Number of surgical procedures (per 100,000 population)                                                                    19
Completeness of death registration with cause-of-death information (%)                                                     2
Name: count, Length: 462, dtype: int64

In [28]:
df_long.duplicated().sum()

np.int64(0)

In [58]:
df_long.isna().sum()

Series Name     0
Series Code     0
Country Name    0
Country Code    0
Year            0
Value           0
dtype: int64

In [59]:
df_long.to_csv("clean_health_data.csv", index=False)

In [60]:
df_long.dtypes

Series Name         str
Series Code         str
Country Name        str
Country Code        str
Year              int64
Value           float64
dtype: object

In [61]:
df_long.groupby("Country Name").size().sort_values(ascending=False)

Country Name
Burkina Faso                 17546
Malawi                       17311
Niger                        17278
Togo                         17265
Rwanda                       17205
Uganda                       17198
Mali                         17193
Mozambique                   17074
Gambia, The                  17053
Burundi                      17027
Madagascar                   17026
Chad                         17012
Central African Republic     16805
Syrian Arab Republic         16801
Sierra Leone                 16776
Congo, Dem. Rep.             16739
Afghanistan                  16689
Yemen, Rep.                  16509
Sudan                        16304
Guinea-Bissau                16263
Liberia                      16190
Eritrea                      16002
Somalia, Fed. Rep.           15662
South Sudan                  15197
Korea, Dem. People's Rep.    14878
dtype: int64

In [62]:
df_long.groupby("Year").size()

Year
1960    4287
1961    4334
1962    4352
1963    4363
1964    4374
1965    4401
1966    4395
1967    4400
1968    4405
1969    4422
1970    4510
1971    4646
1972    4633
1973    4640
1974    4635
1975    4681
1976    4664
1977    4673
1978    4698
1979    4699
1980    4735
1981    4791
1982    4768
1983    4766
1984    4802
1985    4911
1986    4937
1987    4983
1988    4957
1989    4955
1990    6399
1991    6455
1992    6572
1993    6485
1994    6434
1995    6532
1996    6473
1997    6521
1998    6504
1999    6554
2000    8714
2001    8263
2002    8281
2003    8350
2004    8469
2005    8539
2006    8772
2007    8482
2008    8534
2009    8630
2010    9363
2011    8718
2012    8666
2013    8804
2014    8827
2015    9023
2016    8711
2017    8892
2018    8973
2019    8920
2020    8645
2021    8326
2022    7940
2023    7628
2024    6787
dtype: int64

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df_long["Value"], bins=50)

plt.title("Distribution of Health Indicator Values")
plt.xlabel("Value")
plt.ylabel("Frequency")

plt.show()

In [64]:
sorted(df_long["Series Name"].unique())

['AIDS estimated deaths (UNAIDS estimates)',
 'ARI treatment (% of children under 5 taken to a health provider)',
 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
 'Adults (ages 15+) and children (0-14 years) living with HIV',
 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV',
 'Adults (ages 15+) living with HIV',
 'Adults (ages 15-49) newly infected with HIV',
 'Age at first marriage, female',
 'Age at first marriage, male',
 'Age dependency ratio (% of working-age population)',
 'Age dependency ratio, old',
 'Age dependency ratio, young',
 'Age population, age 00, female',
 'Age population, age 00, male',
 'Age population, age 01, female',
 'Age population, age 01, male',
 'Age population, age 02, female',
 'Age population, age 02, male',
 'Age population, age 03, female',
 'Age population, age 03, male',
 'Age population, age 04, female',
 'Age population, age 04, male',
 'Age population, age 05, female',
 'Age population, age 05, male',
 'Age population, age 06, female',
 'Age population, age 06, male',
 'Age population, age 07, female',
 'Age population, age 07, male',
 'Age population, age 08, female',
 'Age population, age 08, male',
 'Age population, age 09, female',
 'Age population, age 09, male',
 'Age population, age 10, female',
 'Age population, age 10, male',
 'Age population, age 11, female',
 'Age population, age 11, male',
 'Age population, age 12, female',
 'Age population, age 12, male',
 'Age population, age 13, female',
 'Age population, age 13, male',
 'Age population, age 14, female',
 'Age population, age 14, male',
 'Age population, age 15, female',
 'Age population, age 15, male',
 'Age population, age 16, female',
 'Age population, age 16, male',
 'Age population, age 17, female',
 'Age population, age 17, male',
 'Age population, age 18, female',
 'Age population, age 18, male',
 'Age population, age 19, female',
 'Age population, age 19, male',
 'Age population, age 20, female',
 'Age population, age 20, male',
 'Age population, age 21, female',
 'Age population, age 21, male',
 'Age population, age 22, female',
 'Age population, age 22, male',
 'Age population, age 23, female',
 'Age population, age 23, male',
 'Age population, age 24, female',
 'Age population, age 24, male',
 'Age population, age 25, female',
 'Age population, age 25, male',
 'Antiretroviral therapy coverage (% of people living with HIV)',
 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)',
 'Birth rate, crude (per 1,000 people)',
 'Births attended by skilled health staff (% of total)',
 'Capital health expenditure (% of GDP)',
 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
 'Cause of death, by injury (% of total)',
 'Cause of death, by non-communicable diseases (% of total)',
 'Cause of death, by other COVID-19 pandemic-related outcomes (% of total)',
 'Children (0-14) living with HIV',
 'Children (ages 0-14) newly infected with HIV',
 'Children orphaned by HIV/AIDS',
 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)',
 'Community health workers (per 1,000 people)',
 'Completeness of birth registration (%)',
 'Completeness of birth registration, female (%)',
 'Completeness of birth registration, male (%)',
 'Completeness of birth registration, rural (%)',
 'Completeness of birth registration, urban (%)',
 'Completeness of death registration with cause-of-death information (%)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, male (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, female (2 prevent ways and reject 3 misconceptions)',
 'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, male (2 prevent ways and reject 3 misconceptions)',
 'Condom use at last high-risk sex, adult female (% ages 15-49)',
 'Condom use at last high-risk sex, adult male (% ages 15-49)',
 'Condom use, population ages 15-24, female (% of females ages 15-24)',
 'Condom use, population ages 15-24, male (% of males ages 15-24)',
 'Consumption of iodized salt (% of households)',
 'Contraceptive prevalence, any method (% of all women ages 15-49)',
 'Contraceptive prevalence, any method (% of married women ages 15-49)',
 'Contraceptive prevalence, any method (% of sexually active unmarried women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of all women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of married women ages 15-49)',
 'Contraceptive prevalence, any modern method (% of sexually active unmarried women ages 15-49)',
 'Current health expenditure (% of GDP)',
 'Current health expenditure per capita (current US$)',
 'Current health expenditure per capita, PPP (current international $)',
 'Death rate, crude (per 1,000 people)',
 'Demand for family planning satisfied by any methods (% of married women with demand for family planning)',
 'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)',
 'Diabetes prevalence (% of population ages 20 to 79)',
 'Diarrhea treatment (% of children under 5 receiving oral rehydration and continued feeding)',
 'Diarrhea treatment (% of children under 5 who received ORS packet)',
 'Domestic general government health expenditure (% of GDP)',
 'Domestic general government health expenditure (% of current health expenditure)',
 'Domestic general government health expenditure (% of general government expenditure)',
 'Domestic general government health expenditure per capita (current US$)',
 'Domestic general government health expenditure per capita, PPP (current international $)',
 'Domestic private health expenditure (% of current health expenditure)',
 'Domestic private health expenditure per capita (current US$)',
 'Domestic private health expenditure per capita, PPP  (current international $)',
 'Exclusive breastfeeding (% of children under 6 months)',
 'External health expenditure (% of current health expenditure)',
 'External health expenditure channeled through government (% of external health expenditure)',
 'External health expenditure per capita (current US$)',
 'External health expenditure per capita, PPP (current international $)',
 'Female headed households (% of households with a female head)',
 'Fertility rate, total (births per woman)',
 'GNI per capita, Atlas method (current US$)',
 'Hospital beds (per 1,000 people)',
 'Human capital index (HCI) (scale 0-1)',
 'Human capital index (HCI), female (scale 0-1)',
 'Human capital index (HCI), female, lower bound (scale 0-1)',
 'Human capital index (HCI), female, upper bound (scale 0-1)',
 'Human capital index (HCI), lower bound (scale 0-1)',
 'Human capital index (HCI), male (scale 0-1)',
 'Human capital index (HCI), male, lower bound (scale 0-1)',
 'Human capital index (HCI), male, upper bound (scale 0-1)',
 'Human capital index (HCI), upper bound (scale 0-1)',
 'Immunization, BCG (% of one-year-old children)',
 'Immunization, DPT (% of children ages 12-23 months)',
 'Immunization, HepB3 (% of one-year-old children)',
 'Immunization, Hib3 (% of children ages 12-23 months)',
 'Immunization, Pol3 (% of one-year-old children)',
 'Immunization, measles (% of children ages 12-23 months)',
 'Immunization, measles second dose (% of children by the nationally recommended age)',
 'Incidence of HIV, ages 15-24 (per 1,000 uninfected population ages 15-24)',
 'Incidence of HIV, ages 15-49 (per 1,000 uninfected population ages 15-49)',
 'Incidence of HIV, ages 50+ (per 1,000 uninfected population ages 50+)',
 'Incidence of HIV, all (per 1,000 uninfected population)',
 'Incidence of malaria (per 1,000 population at risk)',
 'Incidence of tuberculosis (per 100,000 people)',
 'Infant and young child feeding practices, all 3 IYCF (% children ages 6-23 months)',
 'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)',
 'Labor force, female (% of total labor force)',
 'Labor force, total',
 'Life expectancy at birth, female (years)',
 'Life expectancy at birth, male (years)',
 'Life expectancy at birth, total (years)',
 'Lifetime risk of maternal death (%)',
 'Lifetime risk of maternal death (1 in: rate varies by country)',
 'Literacy rate, adult female (% of females ages 15 and above)',
 'Literacy rate, adult male (% of males ages 15 and above)',
 'Literacy rate, adult total (% of people ages 15 and above)',
 'Literacy rate, youth male (% of males ages 15-24)',
 'Literacy rate, youth total (% of people ages 15-24)',
 'Low-birthweight babies (% of births)',
 'Malaria cases reported',
 'Maternal leave benefits (% of wages paid in covered period)',
 'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
 'Maternal mortality ratio (national estimate, per 100,000 live births)',
 'Mortality caused by road traffic injury (per 100,000 people)',
 'Mortality caused by road traffic injury, female (per 100,000 female population)',
 'Mortality caused by road traffic injury, male (per 100,000 male population)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
 'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)',
 'Mortality rate attributed to household and ambient air pollution (per 100,000 population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
 'Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)',
 'Mortality rate attributed to unintentional poisoning (per 100,000 population)',
 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, female (per 100,000 female population)',
 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, male (per 100,000 male population)',
 'Mortality rate, adult, female (per 1,000 female adults)',
 'Mortality rate, adult, male (per 1,000 male adults)',
 'Mortality rate, infant (per 1,000 live births)',
 'Mortality rate, infant, female (per 1,000 live births)',
 'Mortality rate, infant, male (per 1,000 live births)',
 'Mortality rate, neonatal (per 1,000 live births)',
 'Mortality rate, under-5 (per 1,000)',
 'Mortality rate, under-5, female (per 1,000)',
 'Mortality rate, under-5, male (per 1,000)',
 'Net migration',
 'Newborns protected against tetanus (%)',
 'Number of deaths ages 10-14 years',
 'Number of deaths ages 10-14 years, female',
 'Number of deaths ages 10-14 years, male',
 'Number of deaths ages 10-19 years',
 'Number of deaths ages 10-19 years, female',
 'Number of deaths ages 10-19 years, male',
 'Number of deaths ages 15-19 years',
 'Number of deaths ages 15-19 years, female',
 'Number of deaths ages 15-19 years, male',
 'Number of deaths ages 20-24 years',
 'Number of deaths ages 20-24 years, female',
 'Number of deaths ages 20-24 years, male',
 'Number of deaths ages 5-9 years',
 'Number of deaths ages 5-9 years, female',
 'Number of deaths ages 5-9 years, male',
 'Number of infant deaths',
 'Number of infant deaths, female',
 'Number of infant deaths, male',
 'Number of maternal deaths',
 'Number of neonatal deaths',
 'Number of people who are undernourished',
 'Number of stillbirths',
 'Number of surgical procedures (per 100,000 population)',
 'Number of under-five deaths',
 'Number of under-five deaths, female',
 'Number of under-five deaths, male',
 'Number of weeks of maternity leave',
 'Nurses and midwives (per 1,000 people)',
 'Out-of-pocket expenditure (% of current health expenditure)',
 'Out-of-pocket expenditure per capita (current US$)',
 'Out-of-pocket expenditure per capita, PPP (current international $)',
 'People practicing open defecation (% of population)',
 'People practicing open defecation, rural (% of rural population)',
 'People practicing open defecation, urban (% of urban population)',
 'People using at least basic drinking water services (% of population)',
 'People using at least basic drinking water services, rural (% of rural population)',
 'People using at least basic drinking water services, urban (% of urban population)',
 'People using at least basic sanitation services (% of population)',
 'People using at least basic sanitation services, rural (% of rural population)',
 'People using at least basic sanitation services, urban  (% of urban population)',
 'People using safely managed drinking water services (% of population)',
 'People using safely managed drinking water services, rural (% of rural population)',
 'People using safely managed drinking water services, urban (% of urban population)',
 'People using safely managed sanitation services (% of population)',
 'People using safely managed sanitation services, rural (% of rural population)',
 'People using safely managed sanitation services, urban  (% of urban population)',
 'People with basic handwashing facilities including soap and water (% of population)',
 'People with basic handwashing facilities including soap and water, rural (% of rural population)',
 'People with basic handwashing facilities including soap and water, urban (% of urban population)',
 'Physicians (per 1,000 people)',
 'Population ages 0-14 (% of total population)',
 'Population ages 0-14, female',
 'Population ages 0-14, female (% of female population)',
 'Population ages 0-14, male',
 'Population ages 0-14, male (% of male population)',
 'Population ages 00-04, female',
 'Population ages 00-04, female (% of female population)',
 'Population ages 00-04, male',
 'Population ages 00-04, male (% of male population)',
 'Population ages 00-14, total',
 'Population ages 05-09, female',
 'Population ages 05-09, female (% of female population)',
 'Population ages 05-09, male',
 'Population ages 05-09, male (% of male population)',
 'Population ages 10-14, female',
 'Population ages 10-14, female (% of female population)',
 'Population ages 10-14, male',
 'Population ages 10-14, male (% of male population)',
 'Population ages 15-19, female',
 'Population ages 15-19, female (% of female population)',
 'Population ages 15-19, male',
 'Population ages 15-19, male (% of male population)',
 'Population ages 15-64 (% of total population)',
 'Population ages 15-64, female',
 'Population ages 15-64, female (% of female population)',
 'Population ages 15-64, male',
 'Population ages 15-64, male (% of male population)',
 'Population ages 15-64, total',
 'Population ages 20-24, female',
 'Population ages 20-24, female (% of female population)',
 'Population ages 20-24, male',
 'Population ages 20-24, male (% of male population)',
 'Population ages 25-29, female',
 'Population ages 25-29, female (% of female population)',
 'Population ages 25-29, male',
 'Population ages 25-29, male (% of male population)',
 'Population ages 30-34, female',
 'Population ages 30-34, female (% of female population)',
 'Population ages 30-34, male',
 'Population ages 30-34, male (% of male population)',
 'Population ages 35-39, female',
 'Population ages 35-39, female (% of female population)',
 'Population ages 35-39, male',
 'Population ages 35-39, male (% of male population)',
 'Population ages 40-44, female',
 'Population ages 40-44, female (% of female population)',
 'Population ages 40-44, male',
 'Population ages 40-44, male (% of male population)',
 'Population ages 45-49, female',
 'Population ages 45-49, female (% of female population)',
 'Population ages 45-49, male',
 'Population ages 45-49, male (% of male population)',
 'Population ages 50-54, female',
 'Population ages 50-54, female (% of female population)',
 'Population ages 50-54, male',
 'Population ages 50-54, male (% of male population)',
 'Population ages 55-59, female',
 'Population ages 55-59, female (% of female population)',
 'Population ages 55-59, male',
 'Population ages 55-59, male (% of male population)',
 'Population ages 60-64, female',
 'Population ages 60-64, female (% of female population)',
 'Population ages 60-64, male',
 'Population ages 60-64, male (% of male population)',
 'Population ages 65 and above (% of total population)',
 'Population ages 65 and above, female',
 'Population ages 65 and above, female (% of female population)',
 'Population ages 65 and above, male',
 'Population ages 65 and above, male (% of male population)',
 'Population ages 65 and above, total',
 'Population ages 65-69, female',
 'Population ages 65-69, female (% of female population)',
 'Population ages 65-69, male',
 'Population ages 65-69, male (% of male population)',
 'Population ages 70-74, female',
 'Population ages 70-74, female (% of female population)',
 'Population ages 70-74, male',
 'Population ages 70-74, male (% of male population)',
 'Population ages 75-79, female',
 'Population ages 75-79, female (% of female population)',
 'Population ages 75-79, male',
 'Population ages 75-79, male (% of male population)',
 'Population ages 80 and above, female',
 'Population ages 80 and above, male',
 'Population ages 80 and above, male (% of male population)',
 'Population ages 80 and older, female (% of female population)',
 'Population growth (annual %)',
 'Population, female',
 'Population, female (% of total population)',
 'Population, male',
 'Population, male (% of total population)',
 'Population, total',
 'Postnatal care coverage (% mothers)',
 'Poverty headcount ratio at national poverty line (% of population)',
 'Pregnant women receiving prenatal care (%)',
 'Pregnant women receiving prenatal care of at least four visits (% of pregnant women)',
 'Prevalence of HIV, female (% ages 15-24)',
 'Prevalence of HIV, male (% ages 15-24)',
 'Prevalence of HIV, total (% of population ages 15-49)',
 'Prevalence of anemia among children (% of children ages 6-59 months)',
 'Prevalence of anemia among non-pregnant women (% of women ages 15-49)',
 'Prevalence of anemia among pregnant women (%)',
 'Prevalence of anemia among women of reproductive age (% of women ages 15-49)',
 'Prevalence of current tobacco use (% of adults)',
 'Prevalence of current tobacco use, females (% of female adults)',
 'Prevalence of current tobacco use, males (% of male adults)',
 'Prevalence of hypertension (% of adults ages 30-79)',
 'Prevalence of hypertension, female (% of female adults ages 30-79)',
 'Prevalence of hypertension, male (% of male adults ages 30-79)',
 'Prevalence of overweight (% of adults)',
 'Prevalence of overweight (% of children under 5)',
 'Prevalence of overweight (modeled estimate, % of children under 5)',
 'Prevalence of overweight, female (% of children under 5)',
 'Prevalence of overweight, female (% of female adults)',
 'Prevalence of overweight, female (modeled estimate, % of children under 5)',
 'Prevalence of overweight, male (% of children under 5)',
 'Prevalence of overweight, male (% of male adults)',
 'Prevalence of overweight, male (modeled estimate, % of children under 5)',
 'Prevalence of severe wasting, weight for height (% of children under 5)',
 'Prevalence of severe wasting, weight for height, female (% of children under 5)',
 'Prevalence of severe wasting, weight for height, male (% of children under 5)',
 'Prevalence of stunting, height for age (% of children under 5)',
 'Prevalence of stunting, height for age (modeled estimate, % of children under 5)',
 'Prevalence of stunting, height for age, female (% of children under 5)',

In [29]:
series = sorted(df_long["Series Name"].unique())

print(f"Total indicators: {len(series)}")

Total indicators: 462